[terminal.shell]
args = ["new-session", "-A", "-D", "-s", "Kizu"]
program = "/usr/bin/tmux"

[env]
TERM = "alacritty-direct"

[window]
decorations = "None" 
opacity = 0.9 

[window.padding]
x = 0
y = 0 

# Bindings

[[keyboard.bindings]]
action = "Paste"
key = "V"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "Copy"
key = "C"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "SearchForward"
key = "F"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "SearchBackward"
key = "B"
mods = "Control|Shift"

# Appearence

# Font
[font]
size = 12.0

[font.normal]
family = "Roboto Mono"
style = "Regular"

[font.bold]
family = "Roboto Mono"
style = "Bold"

[font.italic]
family = "Roboto Mono"
style = "Italic"

[font.bold_italic]
family = "Roboto Mono"
style = "Bold Italic"


[colors.primary]
background = "#282828"
foreground = "#e2cca9"

[colors.cursor]
text = "#282828"
cursor = "#ffc6be"

[colors.vi_mode_cursor]
text = "#282828"
cursor = "#ff75a0"

[colors.search.matches]
foreground = "#282828"
background = "#7daea3"

[colors.search.focused_match]
foreground = "#282828"
background = "#8bba7f"

[colors.selection]
text = "#282828"
background = "#ffc6be"

[colors.normal]
black = "#1d2021"
red = "#f2594b"
green = "#b0b846"
yellow = "#e9b143"
blue = "#80aa9e"
magenta = "#ff75a0"
cyan = "#7daea3"
white = "#e2cca9"

[colors.bright]
black = "#665c54"
red = "#fb4934"
green = "#8bba7f"
yellow = "#FFAD7D"
blue = "#7daea3"
magenta = "#ff75a0"
cyan = "#80aa9e"
white = "#ffc6be"

[[colors.indexed_colors]]
index = 16
color = "#FFAD7D"

[[colors.indexed_colors]]
index = 17
color = "#ffc6be"
